sandbox_mode = "read-only"
[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp?project_ref=wkkzgyhyarqwxoqcdaul&read_only=true&features=docs%2Cdatabase"

[mcp_servers.shadcn]
command = "npx"
args = [
    "shadcn@latest",
    "mcp",
]

[sandbox_workspace_write]
network_access = true
