-- Leyendas de Bacalar
-- 03 - Constraints, foreign keys and indexes
-- Target Supabase project: ojwxchkgzywteutqxkfg

begin;

set local search_path to public, extensions;

-- 3. LLAVES PRIMARIAS, RESTRICCIONES ÚNICAS Y CHECK
-- ============================================================================

ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_pkey PRIMARY KEY (id);
ALTER TABLE public.admin_audit_logs ADD CONSTRAINT admin_audit_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.ar_markers ADD CONSTRAINT ar_markers_pkey PRIMARY KEY (id);
ALTER TABLE public.ar_scenes ADD CONSTRAINT ar_scenes_pkey PRIMARY KEY (id);
ALTER TABLE public.assets ADD CONSTRAINT assets_pkey PRIMARY KEY (id);
ALTER TABLE public.code_batches ADD CONSTRAINT code_batches_pkey PRIMARY KEY (id);
ALTER TABLE public.code_redemptions ADD CONSTRAINT code_redemptions_pkey PRIMARY KEY (id);
ALTER TABLE public.code_requests ADD CONSTRAINT code_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.content_reviews ADD CONSTRAINT content_reviews_pkey PRIMARY KEY (id);
ALTER TABLE public.cover_templates ADD CONSTRAINT cover_templates_pkey PRIMARY KEY (id);
ALTER TABLE public.creator_applications ADD CONSTRAINT creator_applications_pkey PRIMARY KEY (id);
ALTER TABLE public.creator_onboarding_email_tokens ADD CONSTRAINT creator_onboarding_email_tokens_pkey PRIMARY KEY (id);
ALTER TABLE public.creator_profiles ADD CONSTRAINT creator_profiles_pkey PRIMARY KEY (user_id);
ALTER TABLE public.document_extractions ADD CONSTRAINT document_extractions_pkey PRIMARY KEY (id);
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_pkey PRIMARY KEY (id);
ALTER TABLE public.favorites ADD CONSTRAINT favorites_pkey PRIMARY KEY (user_id, legend_id);
ALTER TABLE public.genres ADD CONSTRAINT genres_pkey PRIMARY KEY (id);
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_pkey PRIMARY KEY (id);
ALTER TABLE public.legend_genres ADD CONSTRAINT legend_genres_pkey PRIMARY KEY (legend_id, genre_id);
ALTER TABLE public.legend_media ADD CONSTRAINT legend_media_pkey PRIMARY KEY (id);
ALTER TABLE public.legend_pages ADD CONSTRAINT legend_pages_pkey PRIMARY KEY (id);
ALTER TABLE public.legend_source_documents ADD CONSTRAINT legend_source_documents_pkey PRIMARY KEY (id);
ALTER TABLE public.legend_versions ADD CONSTRAINT legend_versions_pkey PRIMARY KEY (id);
ALTER TABLE public.legends ADD CONSTRAINT legends_pkey PRIMARY KEY (id);
ALTER TABLE public.mobile_devices ADD CONSTRAINT mobile_devices_pkey PRIMARY KEY (id);
ALTER TABLE public.order_items ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);
ALTER TABLE public.orders ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
ALTER TABLE public.payments ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE public.physical_edition_markers ADD CONSTRAINT physical_edition_markers_pkey PRIMARY KEY (edition_id, marker_id);
ALTER TABLE public.physical_editions ADD CONSTRAINT physical_editions_pkey PRIMARY KEY (id);
ALTER TABLE public.products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE public.reading_progress ADD CONSTRAINT reading_progress_pkey PRIMARY KEY (user_id, legend_id);
ALTER TABLE public.reviews ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);
ALTER TABLE public.roles ADD CONSTRAINT roles_pkey PRIMARY KEY (id);
ALTER TABLE public.scan_logs ADD CONSTRAINT scan_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.shelf_items ADD CONSTRAINT shelf_items_pkey PRIMARY KEY (user_id, legend_id);
ALTER TABLE public.subscription_plans ADD CONSTRAINT subscription_plans_pkey PRIMARY KEY (id);
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.system_settings ADD CONSTRAINT system_settings_pkey PRIMARY KEY (key);
ALTER TABLE public.user_legend_access ADD CONSTRAINT user_legend_access_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);
ALTER TABLE public.users_profile ADD CONSTRAINT users_profile_pkey PRIMARY KEY (id);

ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_code_hash_key UNIQUE (code_hash);
ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_display_code_key UNIQUE (display_code);
ALTER TABLE public.ar_markers ADD CONSTRAINT ar_markers_marker_code_key UNIQUE (marker_code);
ALTER TABLE public.code_redemptions ADD CONSTRAINT unique_code_redemption UNIQUE (code_id);
ALTER TABLE public.creator_onboarding_email_tokens ADD CONSTRAINT creator_onboarding_email_tokens_token_hash_key UNIQUE (token_hash);
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_unique_source_page UNIQUE (source_document_id, page_number);
ALTER TABLE public.genres ADD CONSTRAINT genres_name_key UNIQUE (name);
ALTER TABLE public.legend_pages ADD CONSTRAINT unique_page_per_version UNIQUE (version_id, page_number);
ALTER TABLE public.legend_versions ADD CONSTRAINT unique_legend_version_number UNIQUE (legend_id, version_number);
ALTER TABLE public.legends ADD CONSTRAINT legends_slug_key UNIQUE (slug);
ALTER TABLE public.mobile_devices ADD CONSTRAINT unique_user_device_hash UNIQUE (user_id, device_hash);
ALTER TABLE public.reviews ADD CONSTRAINT unique_review_per_user_legend UNIQUE (user_id, legend_id);
ALTER TABLE public.roles ADD CONSTRAINT roles_name_key UNIQUE (name);
ALTER TABLE public.subscription_plans ADD CONSTRAINT subscription_plans_product_id_key UNIQUE (product_id);
ALTER TABLE public.users_profile ADD CONSTRAINT users_profile_username_key UNIQUE (username);

ALTER TABLE public.access_codes ADD CONSTRAINT valid_access_code_prefix CHECK ((char_length((prefix)::text) >= 2));
ALTER TABLE public.admin_audit_logs ADD CONSTRAINT valid_audit_action CHECK ((char_length((action)::text) >= 3));
ALTER TABLE public.admin_audit_logs ADD CONSTRAINT valid_audit_entity_type CHECK ((char_length((entity_type)::text) >= 3));
ALTER TABLE public.assets ADD CONSTRAINT valid_asset_source CHECK ((((source_type = 'upload'::asset_source_type) AND ((storage_path IS NOT NULL) OR (file_url IS NOT NULL))) OR ((source_type = 'external_url'::asset_source_type) AND (external_url IS NOT NULL))));
ALTER TABLE public.assets ADD CONSTRAINT valid_file_size CHECK (((file_size IS NULL) OR (file_size >= 0)));
ALTER TABLE public.code_batches ADD CONSTRAINT valid_code_batch_prefix CHECK ((char_length((prefix)::text) >= 2));
ALTER TABLE public.code_batches ADD CONSTRAINT valid_code_batch_quantity CHECK ((quantity > 0));
ALTER TABLE public.code_requests ADD CONSTRAINT valid_quantity_requested CHECK ((quantity_requested > 0));
ALTER TABLE public.content_reviews ADD CONSTRAINT valid_reviewed_data CHECK ((((status = 'pending'::content_review_status) AND (reviewed_by IS NULL) AND (reviewed_at IS NULL)) OR (status <> 'pending'::content_review_status)));
ALTER TABLE public.cover_templates ADD CONSTRAINT cover_templates_owner_scope_ck CHECK ((((scope = 'system'::text) AND (owner_id IS NULL)) OR ((scope = 'creator'::text) AND (owner_id IS NOT NULL))));
ALTER TABLE public.cover_templates ADD CONSTRAINT cover_templates_scope_check CHECK ((scope = ANY (ARRAY['system'::text, 'creator'::text])));
ALTER TABLE public.creator_onboarding_email_tokens ADD CONSTRAINT creator_onboarding_token_expiry_check CHECK ((expires_at > created_at));
ALTER TABLE public.creator_profiles ADD CONSTRAINT creator_profiles_profile_visibility_check CHECK ((profile_visibility = ANY (ARRAY['public'::text, 'private'::text])));
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_height_check CHECK (((height IS NULL) OR (height > 0)));
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_page_number_check CHECK ((page_number > 0));
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_ready_has_image CHECK (((status <> 'ready'::text) OR (image_asset_id IS NOT NULL)));
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_render_format_check CHECK ((render_format = ANY (ARRAY['jpg'::text, 'jpeg'::text, 'webp'::text, 'png'::text])));
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_render_scale_check CHECK (((render_scale > (0)::numeric) AND (render_scale <= (4)::numeric)));
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'ready'::text, 'failed'::text, 'archived'::text])));
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_width_check CHECK (((width IS NULL) OR (width > 0)));
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT hotspot_target_coherent CHECK ((((target_type = 'source_document'::text) AND (source_document_id IS NOT NULL) AND (source_page_number IS NOT NULL) AND (page_id IS NULL)) OR ((target_type = 'legend_page'::text) AND (page_id IS NOT NULL) AND (source_document_id IS NULL)) OR ((target_type = 'physical_edition'::text) AND (page_id IS NULL) AND (source_document_id IS NULL) AND (source_page_number IS NULL))));
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_height_check CHECK (((height IS NULL) OR ((height > (0)::numeric) AND (height <= (1)::numeric))));
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_hotspot_type_check CHECK ((hotspot_type = ANY (ARRAY['marker'::text, 'model'::text, 'info'::text, 'ar_scene'::text])));
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_source_page_number_check CHECK (((source_page_number IS NULL) OR (source_page_number >= 1)));
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'in_review'::text, 'published'::text, 'archived'::text])));
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_target_type_check CHECK ((target_type = ANY (ARRAY['source_document'::text, 'legend_page'::text, 'physical_edition'::text])));
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_width_check CHECK (((width IS NULL) OR ((width > (0)::numeric) AND (width <= (1)::numeric))));
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_x_check CHECK (((x >= (0)::numeric) AND (x <= (1)::numeric)));
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_y_check CHECK (((y >= (0)::numeric) AND (y <= (1)::numeric)));
ALTER TABLE public.legend_pages ADD CONSTRAINT valid_page_number CHECK ((page_number > 0));
ALTER TABLE public.legend_source_documents ADD CONSTRAINT legend_source_documents_render_status_check CHECK ((render_status = ANY (ARRAY['not_rendered'::text, 'rendering'::text, 'ready'::text, 'failed'::text])));
ALTER TABLE public.legend_source_documents ADD CONSTRAINT legend_source_documents_rendered_page_count_check CHECK (((rendered_page_count IS NULL) OR (rendered_page_count >= 0)));
ALTER TABLE public.legend_source_documents ADD CONSTRAINT valid_source_document_page_count CHECK (((page_count IS NULL) OR (page_count >= 0)));
ALTER TABLE public.legend_versions ADD CONSTRAINT valid_version_number CHECK ((version_number > 0));
ALTER TABLE public.order_items ADD CONSTRAINT valid_order_item_quantity CHECK ((quantity > 0));
ALTER TABLE public.order_items ADD CONSTRAINT valid_order_item_subtotal CHECK ((subtotal >= (0)::numeric));
ALTER TABLE public.order_items ADD CONSTRAINT valid_order_item_unit_price CHECK ((unit_price >= (0)::numeric));
ALTER TABLE public.orders ADD CONSTRAINT valid_order_total CHECK ((total_amount >= (0)::numeric));
ALTER TABLE public.payments ADD CONSTRAINT valid_card_last_four CHECK (((card_last_four IS NULL) OR ((card_last_four)::text ~ '^[0-9]{4}$'::text)));
ALTER TABLE public.payments ADD CONSTRAINT valid_payment_amount CHECK ((amount >= (0)::numeric));
ALTER TABLE public.physical_editions ADD CONSTRAINT physical_editions_code_quota_check CHECK ((code_quota >= 0));
ALTER TABLE public.physical_editions ADD CONSTRAINT valid_release_year CHECK (((release_year IS NULL) OR (release_year >= 1900)));
ALTER TABLE public.products ADD CONSTRAINT valid_product_price CHECK ((price >= (0)::numeric));
ALTER TABLE public.products ADD CONSTRAINT valid_product_target CHECK ((((product_type = 'digital_legend'::product_type) AND (legend_id IS NOT NULL) AND (edition_id IS NULL)) OR ((product_type = 'physical_book'::product_type) AND (edition_id IS NOT NULL)) OR ((product_type = 'subscription_plan'::product_type) AND (legend_id IS NULL) AND (edition_id IS NULL))));
ALTER TABLE public.reading_progress ADD CONSTRAINT valid_last_page_number CHECK ((last_page_number > 0));
ALTER TABLE public.reading_progress ADD CONSTRAINT valid_progress_percent CHECK (((progress_percent >= (0)::numeric) AND (progress_percent <= (100)::numeric)));
ALTER TABLE public.reviews ADD CONSTRAINT valid_review_rating CHECK (((rating >= 1) AND (rating <= 5)));
ALTER TABLE public.subscription_plans ADD CONSTRAINT valid_subscription_duration CHECK ((duration_days > 0));
ALTER TABLE public.subscription_plans ADD CONSTRAINT valid_subscription_plan_price CHECK ((price >= (0)::numeric));
ALTER TABLE public.subscriptions ADD CONSTRAINT valid_subscription_dates CHECK ((ends_at > starts_at));
ALTER TABLE public.user_legend_access ADD CONSTRAINT valid_access_dates CHECK (((expires_at IS NULL) OR (expires_at > starts_at)));

-- ============================================================================

-- 4. LLAVES FORÁNEAS
-- ============================================================================

ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_assigned_to_user_id_fkey FOREIGN KEY (assigned_to_user_id) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES code_batches(id) ON DELETE CASCADE;
ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_edition_id_fkey FOREIGN KEY (edition_id) REFERENCES physical_editions(id) ON DELETE CASCADE;
ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.admin_audit_logs ADD CONSTRAINT admin_audit_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.ar_markers ADD CONSTRAINT ar_markers_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.ar_markers ADD CONSTRAINT ar_markers_ar_scene_id_fkey FOREIGN KEY (ar_scene_id) REFERENCES ar_scenes(id) ON DELETE CASCADE;
ALTER TABLE public.ar_markers ADD CONSTRAINT ar_markers_created_by_fkey FOREIGN KEY (created_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.ar_markers ADD CONSTRAINT ar_markers_marker_asset_id_fkey FOREIGN KEY (marker_asset_id) REFERENCES assets(id) ON DELETE RESTRICT;
ALTER TABLE public.ar_scenes ADD CONSTRAINT ar_scenes_created_by_fkey FOREIGN KEY (created_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.ar_scenes ADD CONSTRAINT ar_scenes_model_asset_id_fkey FOREIGN KEY (model_asset_id) REFERENCES assets(id) ON DELETE RESTRICT;
ALTER TABLE public.ar_scenes ADD CONSTRAINT ar_scenes_page_id_fkey FOREIGN KEY (page_id) REFERENCES legend_pages(id) ON DELETE CASCADE;
ALTER TABLE public.assets ADD CONSTRAINT assets_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.code_batches ADD CONSTRAINT code_batches_code_request_id_fkey FOREIGN KEY (code_request_id) REFERENCES code_requests(id) ON DELETE SET NULL;
ALTER TABLE public.code_batches ADD CONSTRAINT code_batches_edition_id_fkey FOREIGN KEY (edition_id) REFERENCES physical_editions(id) ON DELETE CASCADE;
ALTER TABLE public.code_batches ADD CONSTRAINT code_batches_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.code_redemptions ADD CONSTRAINT code_redemptions_code_id_fkey FOREIGN KEY (code_id) REFERENCES access_codes(id) ON DELETE RESTRICT;
ALTER TABLE public.code_redemptions ADD CONSTRAINT code_redemptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.code_requests ADD CONSTRAINT code_requests_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creator_profiles(user_id) ON DELETE CASCADE;
ALTER TABLE public.code_requests ADD CONSTRAINT code_requests_edition_id_fkey FOREIGN KEY (edition_id) REFERENCES physical_editions(id) ON DELETE SET NULL;
ALTER TABLE public.code_requests ADD CONSTRAINT code_requests_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.code_requests ADD CONSTRAINT code_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.content_reviews ADD CONSTRAINT content_reviews_legend_version_id_fkey FOREIGN KEY (legend_version_id) REFERENCES legend_versions(id) ON DELETE CASCADE;
ALTER TABLE public.content_reviews ADD CONSTRAINT content_reviews_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.content_reviews ADD CONSTRAINT content_reviews_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES users_profile(id) ON DELETE RESTRICT;
ALTER TABLE public.cover_templates ADD CONSTRAINT cover_templates_background_asset_id_fkey FOREIGN KEY (background_asset_id) REFERENCES assets(id) ON DELETE SET NULL;
ALTER TABLE public.cover_templates ADD CONSTRAINT cover_templates_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.cover_templates ADD CONSTRAINT cover_templates_preview_asset_id_fkey FOREIGN KEY (preview_asset_id) REFERENCES assets(id) ON DELETE SET NULL;
ALTER TABLE public.creator_applications ADD CONSTRAINT creator_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.creator_applications ADD CONSTRAINT creator_applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.creator_onboarding_email_tokens ADD CONSTRAINT creator_onboarding_email_tokens_application_id_fkey FOREIGN KEY (application_id) REFERENCES creator_applications(id) ON DELETE CASCADE;
ALTER TABLE public.creator_onboarding_email_tokens ADD CONSTRAINT creator_onboarding_email_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.creator_profiles ADD CONSTRAINT creator_profiles_cover_asset_id_fkey FOREIGN KEY (cover_asset_id) REFERENCES assets(id) ON DELETE SET NULL;
ALTER TABLE public.creator_profiles ADD CONSTRAINT creator_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.document_extractions ADD CONSTRAINT document_extractions_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES legend_source_documents(id) ON DELETE CASCADE;
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_image_asset_id_fkey FOREIGN KEY (image_asset_id) REFERENCES assets(id) ON DELETE RESTRICT;
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES legend_source_documents(id) ON DELETE CASCADE;
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_thumbnail_asset_id_fkey FOREIGN KEY (thumbnail_asset_id) REFERENCES assets(id) ON DELETE SET NULL;
ALTER TABLE public.document_render_pages ADD CONSTRAINT document_render_pages_version_id_fkey FOREIGN KEY (version_id) REFERENCES legend_versions(id) ON DELETE SET NULL;
ALTER TABLE public.favorites ADD CONSTRAINT favorites_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.favorites ADD CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_ar_scene_id_fkey FOREIGN KEY (ar_scene_id) REFERENCES ar_scenes(id) ON DELETE SET NULL;
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_created_by_fkey FOREIGN KEY (created_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_marker_asset_id_fkey FOREIGN KEY (marker_asset_id) REFERENCES assets(id) ON DELETE RESTRICT;
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_page_id_fkey FOREIGN KEY (page_id) REFERENCES legend_pages(id) ON DELETE CASCADE;
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES legend_source_documents(id) ON DELETE CASCADE;
ALTER TABLE public.interactive_hotspots ADD CONSTRAINT interactive_hotspots_version_id_fkey FOREIGN KEY (version_id) REFERENCES legend_versions(id) ON DELETE SET NULL;
ALTER TABLE public.legend_genres ADD CONSTRAINT legend_genres_genre_id_fkey FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE RESTRICT;
ALTER TABLE public.legend_genres ADD CONSTRAINT legend_genres_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.legend_media ADD CONSTRAINT legend_media_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE RESTRICT;
ALTER TABLE public.legend_media ADD CONSTRAINT legend_media_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.legend_pages ADD CONSTRAINT legend_pages_background_asset_id_fkey FOREIGN KEY (background_asset_id) REFERENCES assets(id) ON DELETE SET NULL;
ALTER TABLE public.legend_pages ADD CONSTRAINT legend_pages_version_id_fkey FOREIGN KEY (version_id) REFERENCES legend_versions(id) ON DELETE CASCADE;
ALTER TABLE public.legend_source_documents ADD CONSTRAINT legend_source_documents_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE RESTRICT;
ALTER TABLE public.legend_source_documents ADD CONSTRAINT legend_source_documents_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.legend_source_documents ADD CONSTRAINT legend_source_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.legend_source_documents ADD CONSTRAINT legend_source_documents_version_id_fkey FOREIGN KEY (version_id) REFERENCES legend_versions(id) ON DELETE SET NULL;
ALTER TABLE public.legend_versions ADD CONSTRAINT legend_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES users_profile(id) ON DELETE RESTRICT;
ALTER TABLE public.legend_versions ADD CONSTRAINT legend_versions_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.legend_versions ADD CONSTRAINT legend_versions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.legends ADD CONSTRAINT legends_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES creator_profiles(user_id) ON DELETE RESTRICT;
ALTER TABLE public.mobile_devices ADD CONSTRAINT mobile_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_assigned_code_id_fkey FOREIGN KEY (assigned_code_id) REFERENCES access_codes(id) ON DELETE SET NULL;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.payments ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.physical_edition_markers ADD CONSTRAINT physical_edition_markers_edition_id_fkey FOREIGN KEY (edition_id) REFERENCES physical_editions(id) ON DELETE CASCADE;
ALTER TABLE public.physical_edition_markers ADD CONSTRAINT physical_edition_markers_marker_id_fkey FOREIGN KEY (marker_id) REFERENCES ar_markers(id) ON DELETE RESTRICT;
ALTER TABLE public.physical_editions ADD CONSTRAINT physical_editions_created_by_fkey FOREIGN KEY (created_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.physical_editions ADD CONSTRAINT physical_editions_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_edition_id_fkey FOREIGN KEY (edition_id) REFERENCES physical_editions(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.reading_progress ADD CONSTRAINT reading_progress_last_page_id_fkey FOREIGN KEY (last_page_id) REFERENCES legend_pages(id) ON DELETE SET NULL;
ALTER TABLE public.reading_progress ADD CONSTRAINT reading_progress_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.reading_progress ADD CONSTRAINT reading_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.scan_logs ADD CONSTRAINT scan_logs_device_id_fkey FOREIGN KEY (device_id) REFERENCES mobile_devices(id) ON DELETE SET NULL;
ALTER TABLE public.scan_logs ADD CONSTRAINT scan_logs_marker_id_fkey FOREIGN KEY (marker_id) REFERENCES ar_markers(id) ON DELETE SET NULL;
ALTER TABLE public.scan_logs ADD CONSTRAINT scan_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.shelf_items ADD CONSTRAINT shelf_items_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.shelf_items ADD CONSTRAINT shelf_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.subscription_plans ADD CONSTRAINT subscription_plans_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES subscription_plans(id) ON DELETE RESTRICT;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.system_settings ADD CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.user_legend_access ADD CONSTRAINT user_legend_access_legend_id_fkey FOREIGN KEY (legend_id) REFERENCES legends(id) ON DELETE CASCADE;
ALTER TABLE public.user_legend_access ADD CONSTRAINT user_legend_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES users_profile(id) ON DELETE SET NULL;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_profile(id) ON DELETE CASCADE;
ALTER TABLE public.users_profile ADD CONSTRAINT users_profile_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- ============================================================================

-- 5. ÍNDICES
-- (no se repiten los índices que respaldan PRIMARY KEY / UNIQUE)
-- ============================================================================

CREATE INDEX idx_access_codes_assigned_user ON public.access_codes USING btree (assigned_to_user_id);
CREATE INDEX idx_access_codes_batch ON public.access_codes USING btree (batch_id);
CREATE INDEX idx_access_codes_edition ON public.access_codes USING btree (edition_id);
CREATE INDEX idx_access_codes_generated_by ON public.access_codes USING btree (generated_by);
CREATE INDEX idx_access_codes_status ON public.access_codes USING btree (status);
CREATE INDEX idx_admin_audit_logs_action ON public.admin_audit_logs USING btree (action);
CREATE INDEX idx_admin_audit_logs_admin ON public.admin_audit_logs USING btree (admin_id);
CREATE INDEX idx_admin_audit_logs_created_at ON public.admin_audit_logs USING btree (created_at);
CREATE INDEX idx_admin_audit_logs_entity ON public.admin_audit_logs USING btree (entity_type, entity_id);
CREATE INDEX idx_admin_audit_logs_severity ON public.admin_audit_logs USING btree (severity);
CREATE INDEX idx_ar_markers_approved_by ON public.ar_markers USING btree (approved_by);
CREATE INDEX idx_ar_markers_created_by ON public.ar_markers USING btree (created_by);
CREATE INDEX idx_ar_markers_marker_asset_id ON public.ar_markers USING btree (marker_asset_id);
CREATE INDEX idx_ar_markers_scene ON public.ar_markers USING btree (ar_scene_id);
CREATE INDEX idx_ar_markers_status ON public.ar_markers USING btree (status);
CREATE INDEX idx_ar_scenes_created_by ON public.ar_scenes USING btree (created_by);
CREATE INDEX idx_ar_scenes_model_asset_id ON public.ar_scenes USING btree (model_asset_id);
CREATE INDEX idx_ar_scenes_page_id ON public.ar_scenes USING btree (page_id);
CREATE INDEX idx_assets_uploaded_by ON public.assets USING btree (uploaded_by);
CREATE INDEX idx_code_batches_code_request_id ON public.code_batches USING btree (code_request_id);
CREATE INDEX idx_code_batches_edition ON public.code_batches USING btree (edition_id);
CREATE INDEX idx_code_batches_generated_by ON public.code_batches USING btree (generated_by);
CREATE INDEX idx_code_batches_status ON public.code_batches USING btree (status);
CREATE INDEX idx_code_redemptions_redeemed_at ON public.code_redemptions USING btree (redeemed_at);
CREATE INDEX idx_code_redemptions_user ON public.code_redemptions USING btree (user_id);
CREATE INDEX idx_code_requests_creator ON public.code_requests USING btree (creator_id);
CREATE INDEX idx_code_requests_edition_id ON public.code_requests USING btree (edition_id);
CREATE INDEX idx_code_requests_legend ON public.code_requests USING btree (legend_id);
CREATE INDEX idx_code_requests_reviewed_by ON public.code_requests USING btree (reviewed_by);
CREATE INDEX idx_code_requests_status ON public.code_requests USING btree (status);
CREATE INDEX idx_content_reviews_created_at ON public.content_reviews USING btree (created_at);
CREATE INDEX idx_content_reviews_reviewed_by ON public.content_reviews USING btree (reviewed_by);
CREATE INDEX idx_content_reviews_status ON public.content_reviews USING btree (status);
CREATE INDEX idx_content_reviews_submitted_by ON public.content_reviews USING btree (submitted_by);
CREATE INDEX idx_content_reviews_version ON public.content_reviews USING btree (legend_version_id);
CREATE UNIQUE INDEX one_pending_review_per_legend_version ON public.content_reviews USING btree (legend_version_id) WHERE (status = 'pending'::content_review_status);
CREATE INDEX cover_templates_owner_idx ON public.cover_templates USING btree (owner_id);
CREATE INDEX cover_templates_scope_idx ON public.cover_templates USING btree (scope) WHERE is_active;
CREATE INDEX idx_cover_templates_background_asset_id ON public.cover_templates USING btree (background_asset_id);
CREATE INDEX idx_cover_templates_preview_asset_id ON public.cover_templates USING btree (preview_asset_id);
CREATE INDEX idx_creator_applications_reviewed_by ON public.creator_applications USING btree (reviewed_by);
CREATE UNIQUE INDEX one_pending_creator_application_per_user ON public.creator_applications USING btree (user_id) WHERE (status = 'pending'::creator_application_status);
CREATE INDEX creator_onboarding_email_tokens_application_id_idx ON public.creator_onboarding_email_tokens USING btree (application_id);
CREATE INDEX creator_onboarding_email_tokens_user_id_idx ON public.creator_onboarding_email_tokens USING btree (user_id);
CREATE INDEX creator_onboarding_email_tokens_valid_idx ON public.creator_onboarding_email_tokens USING btree (token_hash, expires_at) WHERE (consumed_at IS NULL);
CREATE INDEX idx_creator_profiles_cover_asset_id ON public.creator_profiles USING btree (cover_asset_id);
CREATE INDEX idx_document_extractions_source_document_id ON public.document_extractions USING btree (source_document_id);
CREATE INDEX idx_document_render_pages_image_asset ON public.document_render_pages USING btree (image_asset_id);
CREATE INDEX idx_document_render_pages_legend ON public.document_render_pages USING btree (legend_id);
CREATE INDEX idx_document_render_pages_page_status ON public.document_render_pages USING btree (source_document_id, status);
CREATE INDEX idx_document_render_pages_source_page ON public.document_render_pages USING btree (source_document_id, page_number);
CREATE INDEX idx_document_render_pages_thumbnail_asset ON public.document_render_pages USING btree (thumbnail_asset_id);
CREATE INDEX idx_document_render_pages_version_id ON public.document_render_pages USING btree (version_id);
CREATE INDEX idx_favorites_legend ON public.favorites USING btree (legend_id);
CREATE INDEX idx_hotspots_legend ON public.interactive_hotspots USING btree (legend_id);
CREATE INDEX idx_hotspots_page ON public.interactive_hotspots USING btree (page_id);
CREATE INDEX idx_hotspots_source_doc ON public.interactive_hotspots USING btree (source_document_id, source_page_number);
CREATE INDEX idx_hotspots_status ON public.interactive_hotspots USING btree (status);
CREATE INDEX idx_interactive_hotspots_ar_scene_id ON public.interactive_hotspots USING btree (ar_scene_id);
CREATE INDEX idx_interactive_hotspots_created_by ON public.interactive_hotspots USING btree (created_by);
CREATE INDEX idx_interactive_hotspots_marker_asset_id ON public.interactive_hotspots USING btree (marker_asset_id);
CREATE INDEX idx_interactive_hotspots_version_id ON public.interactive_hotspots USING btree (version_id);
CREATE INDEX idx_legend_genres_genre_id ON public.legend_genres USING btree (genre_id);
CREATE INDEX idx_legend_media_asset_id ON public.legend_media USING btree (asset_id);
CREATE UNIQUE INDEX one_primary_media_per_legend_type_context ON public.legend_media USING btree (legend_id, media_type, usage_context) WHERE (is_primary = true);
CREATE UNIQUE INDEX unique_legend_media_asset_type ON public.legend_media USING btree (legend_id, asset_id, media_type, usage_context);
CREATE INDEX idx_legend_pages_background_asset_id ON public.legend_pages USING btree (background_asset_id);
CREATE INDEX idx_legend_source_documents_asset_id ON public.legend_source_documents USING btree (asset_id);
CREATE INDEX idx_legend_source_documents_uploaded_by ON public.legend_source_documents USING btree (uploaded_by);
CREATE INDEX idx_legend_source_documents_version_id ON public.legend_source_documents USING btree (version_id);
CREATE UNIQUE INDEX one_primary_source_document_per_legend ON public.legend_source_documents USING btree (legend_id) WHERE (is_primary_source = true);
CREATE INDEX idx_legend_versions_created_by ON public.legend_versions USING btree (created_by);
CREATE INDEX idx_legend_versions_reviewed_by ON public.legend_versions USING btree (reviewed_by);
CREATE UNIQUE INDEX one_published_version_per_legend ON public.legend_versions USING btree (legend_id) WHERE (status = 'published'::legend_version_status);
CREATE INDEX idx_legends_creator_id ON public.legends USING btree (creator_id);
CREATE INDEX idx_order_items_assigned_code ON public.order_items USING btree (assigned_code_id);
CREATE INDEX idx_order_items_order ON public.order_items USING btree (order_id);
CREATE INDEX idx_order_items_product ON public.order_items USING btree (product_id);
CREATE UNIQUE INDEX unique_assigned_code_per_order_item ON public.order_items USING btree (assigned_code_id) WHERE (assigned_code_id IS NOT NULL);
CREATE INDEX idx_orders_created_at ON public.orders USING btree (created_at);
CREATE INDEX idx_orders_status ON public.orders USING btree (status);
CREATE INDEX idx_orders_user ON public.orders USING btree (user_id);
CREATE INDEX idx_payments_order ON public.payments USING btree (order_id);
CREATE INDEX idx_payments_provider ON public.payments USING btree (provider);
CREATE INDEX idx_payments_status ON public.payments USING btree (status);
CREATE INDEX idx_physical_edition_markers_marker_id ON public.physical_edition_markers USING btree (marker_id);
CREATE INDEX idx_physical_editions_created_by ON public.physical_editions USING btree (created_by);
CREATE UNIQUE INDEX unique_physical_edition_per_legend ON public.physical_editions USING btree (legend_id, edition_name);
CREATE INDEX idx_products_edition ON public.products USING btree (edition_id);
CREATE INDEX idx_products_legend ON public.products USING btree (legend_id);
CREATE INDEX idx_products_status ON public.products USING btree (status);
CREATE INDEX idx_products_type ON public.products USING btree (product_type);
CREATE INDEX idx_reading_progress_last_page_id ON public.reading_progress USING btree (last_page_id);
CREATE INDEX idx_reading_progress_legend ON public.reading_progress USING btree (legend_id);
CREATE INDEX idx_reviews_legend ON public.reviews USING btree (legend_id);
CREATE INDEX idx_reviews_status ON public.reviews USING btree (status);
CREATE INDEX idx_reviews_user ON public.reviews USING btree (user_id);
CREATE INDEX idx_scan_logs_created_at ON public.scan_logs USING btree (created_at);
CREATE INDEX idx_scan_logs_device_id ON public.scan_logs USING btree (device_id);
CREATE INDEX idx_scan_logs_marker ON public.scan_logs USING btree (marker_id);
CREATE INDEX idx_scan_logs_user ON public.scan_logs USING btree (user_id);
CREATE INDEX idx_shelf_items_legend_id ON public.shelf_items USING btree (legend_id);
CREATE INDEX idx_subscription_plans_status ON public.subscription_plans USING btree (status);
CREATE INDEX idx_subscriptions_dates ON public.subscriptions USING btree (starts_at, ends_at);
CREATE INDEX idx_subscriptions_order_id ON public.subscriptions USING btree (order_id);
CREATE INDEX idx_subscriptions_plan ON public.subscriptions USING btree (plan_id);
CREATE INDEX idx_subscriptions_status ON public.subscriptions USING btree (status);
CREATE INDEX idx_subscriptions_user ON public.subscriptions USING btree (user_id);
CREATE INDEX idx_system_settings_updated_by ON public.system_settings USING btree (updated_by);
CREATE INDEX idx_user_legend_access_legend ON public.user_legend_access USING btree (legend_id);
CREATE INDEX idx_user_legend_access_source ON public.user_legend_access USING btree (access_source);
CREATE INDEX idx_user_legend_access_status ON public.user_legend_access USING btree (status);
CREATE INDEX idx_user_legend_access_user ON public.user_legend_access USING btree (user_id);
CREATE UNIQUE INDEX unique_free_access_per_user_legend ON public.user_legend_access USING btree (user_id, legend_id) WHERE (access_source = 'free'::user_access_source);
CREATE UNIQUE INDEX unique_user_legend_access_by_source ON public.user_legend_access USING btree (user_id, legend_id, access_source, source_id) WHERE (source_id IS NOT NULL);
CREATE INDEX idx_user_roles_assigned_by ON public.user_roles USING btree (assigned_by);
CREATE INDEX idx_user_roles_role_id ON public.user_roles USING btree (role_id);

-- ============================================================================

commit;
